import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { getItemFromLocalStorageById, updateItemFromLocalStorageById } from "@/utils/storage";

export default function Home() {
  const router = useRouter();
  const [curso, setCurso] = useState({});
  const [status, setStatus] = useState("disabled");
  useEffect(() => {
    if (router.isReady) {
      fetchCursos();
    }
  }, [router.isReady]);

  const fetchCursos = async () => {
    const id = router.query.id;
    if (id) {
      const curso = getItemFromLocalStorageById('cursos', id)

      if (curso) {
        setCurso(curso);
      }
    }
  };

  const handleEdit = () => {
    if (status === 'disabled') {
      setStatus('enabled');
    } else if (status === 'enabled') {
      updateCurso();
    }
  }

  const updateCurso = async () => {
    updateItemFromLocalStorageById('cursos', curso)

    await router.push("/cursos");
  }

  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 3</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container my-3">
        <h1>Información:</h1>
        <div className="form-group">
          <label htmlFor="title">Nombre:</label>
          <input
            type="text"
            className="form-control my-1"
            id="title"
            value={curso.title}
            onChange={(e) => setCurso({
              id: curso.id,
              title: e.target.value
            })}
            disabled={status === 'disabled'}
          />
        </div>
        <button type="submit" className="btn btn-primary" onClick={handleEdit}>
          {
            status === 'disabled' ? 'Editar' : 'Guardar'
          }
        </button>
      </main>
    </>
  );
}
