import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { getItemsFromLocalStorage, removeItemFromLocalStorageById } from "@/utils/storage";

export default function Home() {
  const router = useRouter();
  const [cursos, setCursos] = useState([]);

  useEffect(() => {
    fetchCursos();
  }, []);

  const fetchCursos = async () => {
    const cursos = getItemsFromLocalStorage('cursos');
    setCursos(cursos);
  };

  const handleDelete = async (id) => {
    removeItemFromLocalStorageById('cursos', id);

    await fetchCursos();
  };

  const handleStudents = async (id) => {
    await router.push(`/cursos/estudiantes/${id}`)
  }

  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 3</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="buttons my-3">
          <button className="btn btn-info" onClick={() => {
            router.push('/cursos/agregar')
          }}>Agregar Curso</button>
        </div>
        <table className="table table-striped">
          <thead>
            <tr>
              <th>Curso</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {cursos.map(({ id, title }) => (
              <tr key={id}>
                <td>{title}</td>
                <td>
                  <button
                    className="btn btn-success"
                    onClick={() => {
                      router.push(`/cursos/${id}`);
                    }}
                  >
                    Modificar
                  </button>{" "}
                  <button
                    className="btn btn-info"
                    onClick={() => {
                      handleStudents(id);
                    }}
                  >
                    Asignar Estudiantes
                  </button>{" "}
                  <button
                    className="btn btn-danger"
                    onClick={() => {
                      handleDelete(id);
                    }}
                  >
                    Eliminar
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
}
