import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { getItemsFromLocalStorage, removeItemFromLocalStorageById } from "@/utils/storage";

export default function Home() {
  const router = useRouter();
  const [students, setStudents] = useState([]);
  useEffect(() => {
    fetchStudents();
  }, []);

  const fetchStudents = async () => {
    const students = getItemsFromLocalStorage('estudiantes');
    setStudents(students);
  };

  const handleDelete = async (id) => {
    removeItemFromLocalStorageById('estudiantes', id);

    await fetchStudents();
  };

  return (
    <>
      <Head>
        <title>Proyecto de IS2 - Fase 3</title>
        <meta name="description" content="Generated by Proyecto de IS2" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="buttons my-3">
          <button className="btn btn-info" onClick={() => {
            router.push('/estudiantes/agregar')
          }}>Agregar Estudiante</button>
        </div>
        <table className="table table-striped">
          <thead>
            <tr>
              <th>Estudiante</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {students.map(({ id, title }) => (
              <tr key={id}>
                <td>{title}</td>
                <td>
                  <button
                    className="btn btn-success"
                    onClick={() => {
                      router.push(`/estudiantes/${id}`);
                    }}
                  >
                    Modificar
                  </button>{" "}
                  <button
                    className="btn btn-danger"
                    onClick={() => {
                      handleDelete(id);
                    }}
                  >
                    Eliminar
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
}
